---
title: "Prepare Dynamic World metrics"
output: html_document
date: 2025-04-23
---

Author: Matt Macander, ABR
Usage: Script should be executed in R 4.3.1+.
Description: "Prepare Dynamic World metrics" prepares ancillary rasters from compiled Dynamic World time-series

# Dynamic World Metrics

The Dynamic World V1 product (DW, https://developers.google.com/earth-engine/datasets/catalog/GOOGLE_DYNAMICWORLD_V1) is generated for all Sentinel 2 granules with <35% cloud cover. It is a 10 m resolution product with 9 classes. It can be summarized to provide continuous and categorical products that characterize the snow phenology and land cover dynamics at fine spatial resolution.

Initial exploratory work (v20240626 and v20240709) was conducted through July 2024 for a Susitna Wolf habitat study. 

The current analysis (v20250414), conducted through April 2025, builds on the earlier analysis. It covers the Mentasta Lake study area, and the algorithm is extended to cover the full AKVeg-Map study area (all of Alaska and a portion of northwest Canada).

The exploratory work included a snow regime analysis, monthly summaries of water and flooded vegetation frequency, and summaries of all DW classes for both a snow-covered and snow-free season. Because the snow regime analysis was computationally intensive, and showed some artificial patterns in treed areas, it was not extended to the full study area.  Instead, we focused on monthly summaries of all 9 DW classes for the months May–September, which can be summarized to similar metrics as the water and (snow-free season) land cover metrics from the prior version.

## Tiling
To constrain compute requirements, we analyzed one Military Grid Reference System (MGRS) tile at a time. The MGRS tiles are nominally 100 km (10,000 x 10,000 10-m pixels) but the Sentinel 2 version has an additional buffer of about 10 km; in addition, there is extensive overlap at the edges of UTM zones. The study area includes MGRS tiles from 10 UTM zones (Zones 1-8 59, and 60 in the northern hemisphere, or EPSG 32601-32608, 32659, and 32660).

The overlaps require extra storage and compute (Bauer-Marschallinger and Falkner 2023). To greatly reduce that overlap, we applied the Remove Overlap tool from ArcGIS Pro 3.4 (Thiessen method) to remove all overlap, then applied a 100-m geodesic buffer to add a small amount of overlap back to avoid gaps in the final mosaics.

## Filtering
The full time-series of images was analyzed, combining all years for a single MGRS tile and a single calendar month (e.g. all May images from the available years, 2016–2024 were analyzed together). Some duplicate images were present when a single S2 collect was processed more than once. To remove all but one image in these cases, we analyzed only one image from each unique date (e.g. 2020-05-10). No other filtering was applied.

## Masking
Dynamic World products have a cloud and cloud-shadow mask applied, and no additional quality masking was performed.

## Monthly Counts
The count of DW classes for each monthly summary raster was based on the label assignment in the individual maps. The relative probabilities for different classes in the individual maps was not considered. 

## Summary Metrics
For initial summary metrics, the May–September counts were combined to a single total. Then the counts were converted to a frequency percentage, with special treatement of the 'snow_and_ice' class because it represents a winter seasonal condition. For all other classes, the percentage was calculated as the count of that DW class divided by the total of all DW observations that were not snow_and_ice (pct_nonsnow_DWCLASS). For snow_and_ice, it was calculated as the count of snow_and_ice divided by the grand total of all DW observations (pct_snow_and_ice). 

In addition, two versions of the most common (modal) DW class were calculated. modal_nonsnow_dw_class was the modal class, excluding all snow_and_ice observations; and modal_dw_class was the modal class without any exclusions. The frequency of both modal classes was also stored, as an indicator of how dominant that class was for the pixel.

Finally, the total count of DW observations for each pixel was calculated. Percentages were scaled 0-100. Rasters were stored as 8bit unsigned byte.

pct_nonsnow_bare: percentage of non-snow DW observations that are Bare
pct_nonsnow_built: percentage of non-snow DW observations that are Built
pct_nonsnow_crops: percentage of non-snow DW observations that are Crops
pct_nonsnow_flooded_vegetation: percentage of non-snow DW observations that are Flooded Vegetation
pct_nonsnow_grass: percentage of non-snow DW observations that are Grass
pct_nonsnow_shrub_and_scrub: percentage of non-snow DW observations that are Shrub and Scrub
pct_nonsnow_tree: percentage of non-snow DW observations that are Tree
pct_nonsnow_water: percentage of non-snow DW observations that are Water
pct_snow: percentage of DW observations that are Snow and Ice
pct_modal_nonsnow_dw: percentage of non-snow DW observations in modal (most frequent) non-snow class.
pct_modal_dw: percentage of DW observations in modal (most frequent) class.
modal_dw_class: Modal non-snow DW class
modal_nonsnow_dw_class: Modal DW class (including snow)
n: Total number of DW observations, May-September. 254 indicates value >= 254.

## Workflow

1. Generate MGRS tile polygons with 100 m overlap
    
1. Run GEE script s2_dynamic_world_lc_metrics_v20250414_mgrs.js 

    https://code.earthengine.google.com/?scriptPath=users%2Fmmacander%2Fakveg_map%3Adynamic_world_metrics%2Fs2_dynamic_world_lc_metrics_v20250414_mgrs.js
    https://code.earthengine.google.com/a0bea63ac42cbac1a26c3d622aba7267  (link generated 2025-04-23)

    Static copy saved in this code repo.

    Generates monthly rasters for each MGRS tile. Saves result to GCS bucket.
1. Run 05b_data_dynamic_world/dw_months_to_cog_backed_ic.ipynb

    Create and manage the cloud-backed image collection.

1. Run GEE script dynamic_world_metrics/s2_dynamic_world_lc_metrics_v20240414_akalb

    https://code.earthengine.google.com/?scriptPath=users%2Fmmacander%2Fakveg_map%3Adynamic_world_metrics%2Fs2_dynamic_world_lc_metrics_v20240414_akalb.js
    https://code.earthengine.google.com/265fa1ef2490a07f315d6f27465e8bc4  (link generated 2025-04-23)

    Mosaics MGRS results into 5 monthly rasters for study area (on-the-fly).
  
    Combines monthly rasters to June/July/August and/or May-Sept sums.

    Calculates standardized percentage metrics and modal classes.

    Exports results to tiled or study area rasters in AKVeg-Map CRS.

1. Run second block in 05b_data_dynamic_world/dw_months_to_cog_backed_ic.ipynb

    Create and manage the cloud-backed image collection for percentage AKALB tiles.
1. Check results using GEE script 

    https://code.earthengine.google.com/?scriptPath=users%2Fmmacander%2Fakveg_map%3Adynamic_world_metrics%2Fs2_dynamic_world_lc_metrics_v20250414_viz
    https://code.earthengine.google.com/c7d98c84222c428e799d5e3ec9838654 (link generated 2025-04-24)


## References

Bauer-Marschallinger, B. and Falkner, K., 2023. Wasting petabytes: A survey of the Sentinel-2 UTM tiling grid and its spatial overhead. ISPRS Journal of Photogrammetry and Remote Sensing, 202, pp.682-690. https://www.sciencedirect.com/science/article/pii/S0924271623001971