---
title: "predictor_workflow_2024"
author: "Matt Macander"
date: "2024-03-09"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

Get updated disturbance data
Fire (Alaska)
Fire (Canada)

Merge polygon data, create raster versions including most recent fire year layer for simple raster filtering

```{r sentinel 2 composites assess need for index bands}
library(tidyverse)
library(sf)
library(fs)
library(glue)

wd <- path('/data/gis/gis_projects/2024/24-224_Land_Cover_Metrics_Susitna_Wolf/sentinel2_gMedian')

sample_csv <- dir_ls('/data/gis/gis_base/GEE/GEE_Exports/2024_alaska', glob='*10000*.csv')

# file_copy(sample_csv, wd)

sample <- read_csv(path(wd, 'sample_10000_v20230330_gMedian_indices_v_refl_indices_20240308.csv')) %>%
  rename(geo = `.geo`, id=`system:index`) %>%
  mutate(geo = str_sub(geo, 32, -3),
         latitude = as.numeric(str_split_i(geo, ',', 2)),
         longitude = as.numeric(str_split_i(geo, ',', 1))) %>%
  select(-geo) %>%
  pivot_longer(cols=starts_with('season'), names_sep='_', names_to=c('season','metric','method')) %>%
  mutate(method = if_else(is.na(method), 'gMedian', method)) %>%
  filter(!metric %in% c('blue','green','red','rededge1','rededge2','rededge3','rededge4','nir','swir1','swir2','n','tier')) %>%
  pivot_wider(names_from=method, values_from=value)
         
ggplot(sample %>% filter(metric=='nbr'), aes(x=refl, y=gMedian)) + 
  geom_abline(slope = 1, intercept = 0, linetype = "dashed", color = "red") +
  scale_fill_viridis_c(trans = "log", breaks=c(1,3,10,30,100,300,1000,3000), name="No. obs") +
  stat_smooth(method = "lm", se=FALSE, color = "black", linetype = "dashed", show.legend=FALSE) +
  geom_bin2d(bins=100) + 
  xlab(glue("Metrics calculated from gMedian Reflectance")) +
  ylab(glue("Metrics calculated as gMedian")) +
  labs(title=glue("gMedian vs. gMedian Reflectance Metrics")) +
  # facet_wrap(vars(metric), scales='free')
  # facet_grid(metric ~season, scales='free')
  facet_wrap(vars(season), scales='free')


  # # facet_wrap(plot_datasetId ~ .) +
  # val_plot_geom_list +
  # stat_smooth(se=FALSE, color = "red", linetype = "solid", show.legend=FALSE, size=0.5) +
  # stat_smooth(method = "lm", se=FALSE, color = "black", linetype = "dashed", show.legend=FALSE) +
  # coord_fixed(1, c(-5, 105), c(-5,105)) +
  # geom_label(data=df_eq, aes(x = 5, y = 94,label=paste("r^2 ==", r2_score,sep='')), parse = TRUE, hjust=0, vjust=0,
  #            size=labelSize, color = "black", fill="white", label.padding=unit(0.1,"lines"))+
  # geom_label(data=df_eq, aes(x = 5, y = 84,label=paste("rmse ==", rmse,sep='')), parse = TRUE, hjust=0, vjust=0,
  #            size=labelSize, color = "black", fill="white", label.padding=unit(0.1,"lines"))+
  # geom_label(data=df_eq, aes(x = 5, y = 74,label=paste("bias ==", bias,sep='')), parse = TRUE, hjust=0, vjust=0,
  #            size=labelSize, color = "black", fill="white", label.padding=unit(0.1,"lines"))+
  # geom_label(data=df_eq, aes(x = 5, y = 64,label=paste("slope ==", slope,sep='')),parse = TRUE, hjust=0, vjust=0,
  #            size=labelSize, color = "black", fill="white", label.padding=unit(0.1,"lines"))+#
  # xlab(glue("Observed {name} Top Cover (%)")) +
  # ylab(glue("Predicted {name} Top Cover (%)")) +
  # labs(title=glue("Predicted vs. Observed {name} Top Cover"),
  #         # subtitle="subtitle",
  #         caption=rmdPath) +
    
```

