---
title: "Pheno analysis by image areas"
format: html
editor: source
---

```{r}
library(tidyverse)
library(RPostgres)
library(dbplyr)
library(lubridate)
library(fs)
library(glue)
library(janitor)
library(purrr)
library(sf)
library(mapview)
library(ranger)
library(gdalUtilities)
library(terra)
library(exifr)
library(exactextractr)
library(spsurvey)
library(readxl)
library(flextable)
library(ftExtra)
library(officer)
library(here)

if (.Platform$OS.type == "unix") {
  p <- "/home/shared/projects/"
  w <- "/data/gis/"
} else {
  p <- "P:/"
  w <- "W:/"
}

options(scipen = 999)

geeDir <- path(w, "gis_base/GEE/GEE_Exports")
```

```{r open raster}
modis_pheno_normals <- rast(path(w, "raster_base/Alaska/AKVegMap/MODIS_Phenology/MCD43A4_V61_Normals/mcd43a4_061_ndvi_seasonal_doy_percentiles_v20250128_3338_100m.tif"))
crs(modis_pheno_normals) <- "EPSG:3338"

names(modis_pheno_normals)

aoi1 <- read_sf(path(w, "raster_base/Alaska/AKVegMap/EVWHS/nome_beaver/aois/nb_needed_01.shp"))
aoi1_3338 <- project(vect(aoi1), modis_pheno_normals)

aoi1_x_modis <- crop(modis_pheno_normals, aoi1_3338, mask=TRUE)
aoi1_x_modis_freq <- freq(aoi1_x_modis, wide=TRUE) |>
  t()

aoi1_x_modis_p75s <- freq(aoi1_x_modis['doy_start_ndvi_p075_of_max'])
aoi1_x_modis_p80s <- freq(aoi1_x_modis['doy_start_ndvi_p080_of_max'])
aoi1_x_modis_p85s <- freq(aoi1_x_modis['doy_start_ndvi_p085_of_max'])
aoi1_x_modis_p90s <- freq(aoi1_x_modis['doy_start_ndvi_p090_of_max'])
aoi1_x_modis_p95s <- freq(aoi1_x_modis['doy_start_ndvi_p095_of_max'])
```

```{r mentasta}
mentasta <- read_sf(path(w, "raster_base/Alaska/AKVegMap/gdrive_akveg/AKVEG ABR/gis/project_areas/MentastaLake_MapDomain_3338.shp"))
mentasta_3338 <- project(vect(mentasta), modis_pheno_normals)

mentasta_x_modis <- crop(modis_pheno_normals, mentasta_3338, mask=TRUE)
mentasta_x_modis_freq <- freq(mentasta_x_modis, wide=TRUE) |>
  t()

```