---
title: "Fire history, old links and code"
output: html_document
date: "2024-04-23"
---

Author: Matt Macander, ABR
Usage: Script should be executed in R 4.3.1+.
Description: Scripts in 05a_data_disturbance compile and harmonize the latest fire history data for use in AKVeg-Map and other applications.

# Fire History

OLD, Previous
Alaska, downloaded 2024-09-12:
https://blm-egis.maps.arcgis.com/apps/instant/portfolio/index.html?appid=240bd83e9ba34a63b46f7d18c524cb73&locale=en&sectionId=924f70cc3ee9419c81a77b46216f65b1
pro json to feature tool

Alaska, downloaded 2024-03-09:
https://fire.ak.blm.gov/predsvcs/maps.php
https://fire.ak.blm.gov/content/maps/aicc/Data/Data%20(zipped%20filegeodatabases)/AlaskaFireHistory_PerimeterPolygons_gdb.zip
previous, thru 2022
https://fire.ak.blm.gov/content/maps/aicc/Data/Data%20(zipped%20filegeodatabases)/Alaska_Fire_History_Perimeters_Polygons_1940_2022.zip

Canada, downloaded 2024-03-09:
https://cwfis.cfs.nrcan.gc.ca/downloads/nbac/

https://cwfis.cfs.nrcan.gc.ca/datamart/download/nbac

https://open.canada.ca/data/en/dataset/cdfc2d7b-c046-4bf0-90ac-4897232619e1


```{r ingest and standardize on 3338}
ak_20240912 <- read_sf(path(w, 'vector_base/Alaska/Statewide/Fire/Provisional/fire_2024.gdb'), layer='WFIGS_Interagency_Perimeters_YearToDate_20240912') %>%
  mutate(source = 'WFIGS_Interagency_Perimeters_YearToDate, downloaded 2024-09-12',
         fire_year = 2024) %>%
  select(source, fire_year) %>%
  st_transform(3338) %>%
  st_set_geometry("geometry")

ak_firepoly <- read_sf(path(w, 'vector_base/Alaska/Statewide/Fire/AlaskaFireHistory_PerimeterPolygons_gdb_20240309/AlaskaFireHistory_Polygons.gdb'),
                       layer='AK_fire_location_polygons_AKAlbersNAD83') %>%
  rename(geometry = Shape) %>%
  select(fire_year = FIREYEAR) %>%
  mutate(source = 'AK_fire_location_polygons_AKAlbersNAD83 with 2023, downloaded 2024-03-09',
         fire_year = as.integer(fire_year))

#1986-2022
can_nbac <- read_sf(path(w, 'vector_base/Canada/Fire_History/20240308/nbac_1986_to_2022_20230630/nbac_1986_to_2022_20230630.shp')) %>%
  # rename(geometry = Shape) %>%
  select(fire_year = YEAR) %>%
  mutate(source = 'nbac_1986_to_2022_20230630.shp') %>%
  st_make_valid() %>%
  st_transform(3338)

#2023
can_2023 <- read_sf(path(w, 'vector_base/Canada/Fire_History/20240308/prot_current_fire_polys_20240309/prot_current_fire_polys.shp')) %>%
  # rename(geometry = Shape) %>%
  select(fire_year = FIRE_YEAR) %>%
  mutate(source = 'prot_current_fire_polys.shp for 2023, downloaded 2024-03-09') %>%
  st_make_valid() %>%
  st_transform(3338)

can_nfdb <- read_sf(path(w, 'vector_base/Canada/Fire_History/20240308/NFDB_poly 20240308/NFDB_poly_20210707.shp')) %>%
  # rename(geometry = Shape) %>%
  select(fire_year = YEAR, DECADE) %>%
  st_make_valid()
  
#Pre-1986
can_nfdb_thru_1985 <- can_nfdb %>%
  mutate(source = 'NFDB_poly_20210707.shp') %>%
  #Exclude fires from NBAC record and -9999 fires
  filter(between(fire_year, 0, 1986)) %>%
  st_transform(3338) %>%
  select(fire_year, source)

#Unknown but decade known
can_nfdb_unk <- can_nfdb %>%
  # rename(geometry = Shape) %>%
  mutate(source = 'NFDB_poly_20210707.shp, estimated fire_year based on decade') %>%
  #-9999 fires, refer to decade
  filter(fire_year == -9999) %>%
  st_transform(3338) %>%
  mutate(fire_year_start = as.integer(str_split_i(DECADE, '-', 1)),
         fire_year_end   = as.integer(str_split_i(DECADE, '-', 2)),
         fire_year = fire_year_start + 5) %>%
  select(fire_year, source)

can_firepoly_3338 <- bind_rows(can_nfdb_thru_1985, can_nbac, can_2023, can_nfdb_unk) %>%
  arrange(fire_year)

ak_above <- read_sf(path(w, 'gis_projects/2022/22-301_NASA_ABoVE_Biome_Shift/akvegmap_v2/studyAreas',
                    'ABoVE_Alaska_3parts_Buff10km_BuffMinus5km_Simplify5km_3338_v20230328.shp')) %>%
  st_zm(drop=T)
ak_above


ak_above_union <- st_union(ak_above)
can_firepoly_3338_akabove <- st_intersection(can_firepoly_3338, ak_above_union)

# akcan_firepoly_3338 <- bind_rows(ak_20240912, ak_firepoly, can_firepoly_3338) %>%
#   arrange(fire_year)
# write_sf(akcan_firepoly_3338, path(w, 'vector_base/Alaska/Statewide/Fire/akcan_firepoly_thru_2023_v20240309.shp'))


akcan_above_firepoly_3338 <- bind_rows(ak_20240912, ak_firepoly, can_firepoly_3338_akabove) %>%
  arrange(fire_year) %>%
  st_zm(drop=T)
write_sf(akcan_above_firepoly_3338, path(w, 'vector_base/Alaska/Statewide/Fire/akcan_above_firepoly_thru_2023_wProvisionalAK2024_v20240912.shp'))

by_year <- akcan_firepoly_3338 %>% st_drop_geometry() %>% group_by(fire_year) %>% tally()
akcan_firepoly_3338 %>% st_drop_geometry() %>% group_by(source) %>% tally()

```

```{r rasterize}
akcan_firepoly_3338 <- read_sf(path(w, 'vector_base/Alaska/Statewide/Fire/akcan_firepoly_thru_2023_v20240309.shp')) %>%
  mutate(fire_year = as.integer(fire_year))

# st_cast needed if using R created object directly but not after reading merged shapefile
# akcan_firepoly_3338 <- st_cast(akcan_firepoly_3338, 'MULTIPOLYGON')
akcan_firepoly_3338_vect <- vect(akcan_firepoly_3338)

ak_above <- read_sf(path(w, 'gis_projects/2022/22-301_NASA_ABoVE_Biome_Shift/akvegmap_v2/studyAreas',
                    'ABoVE_Alaska_3parts_Buff10km_BuffMinus5km_Simplify5km_3338_v20230328.shp')) %>%
  st_zm(drop=T)

# Use full bounding box of larger Yukon SA vs. the NAB SA
# akyuk_rast <- rast('/data/gis/gis_projects/2019/19-301_ABoVE_Biome_Shift/akvegmap_v2/studyAreas/AKVEG_ModelArea_Rasters_20230330/AlaskaYukon_MapDomain_10m_3338.tif')
# akyuk_sf <- read_sf(path(w, 'gis_projects/2019/19-301_ABoVE_Biome_Shift/akvegmap_v2/studyAreas/AKVEG_Regions_20230330/AKVEG_Regions.gdb'),
                    # layer='AlaskaYukon_MapDomain_3338')

fire_snap_30m_3338 <- rast(resolution=30, crs='EPSG:3338', extent=c(-15,15,-15,15))
fire_snap_30m_3338

fire_30m_3338 <- extend(fire_snap_30m_3338, akcan_firepoly_3338, snap='out')
fire_30m_3338

#SLOOOOW
akcan_fire_rast <- rasterize(akcan_firepoly_3338_vect, fire_30m_3338, 'fire_year', fun='max', datatype='INT2U',
                          filename='/data/gis/gis_projects/2022/22-301_NASA_ABoVE_Biome_Shift/akvegmap_v2/flt32_mrfy_akcan_1917_2024p_30m_3338_v20240912.tif')

gdal_translate('/data/gis/gis_projects/2022/22-301_NASA_ABoVE_Biome_Shift/akvegmap_v2/flt32_mrfy_akcan_1917_2024p_30m_3338_v20240912.tif',
               '/data/gis/gis_projects/2022/22-301_NASA_ABoVE_Biome_Shift/akvegmap_v2/mrfy_akcan_1917_2024p_30m_3338_v20240912.tif',
               ot='UInt16', of='COG', a_nodata=0, co=c("OVERVIEWS=IGNORE_EXISTING", "RESAMPLING=MODE", "COMPRESS=DEFLATE", "PREDICTOR=2", "BIGTIFF=IF_SAFER", "NUM_THREADS=16"))

#10m version, Alaska and Yukon bbox only
#Note this does make the bbox a bit larger than necessary, (0,0) is a bit south of the data extent
fire_snap_10m_3338 <- rast(resolution=10, crs='EPSG:3338', extent=c(-5,5,-5,5))
akyuk <- ak_above %>%
  filter(Region == 'North American Beringia and TNP')
fire_10m_3338 <- extend(fire_snap_10m_3338, akyuk, snap='out')
fire_10m_3338

#SLOOOOW
akyuk_fire_rast <- rasterize(akcan_firepoly_3338_vect, fire_10m_3338, 'fire_year', fun='max',
                          filename='/data/gis/gis_projects/2019/19-301_ABoVE_Biome_Shift/akvegmap_v2/flt32_mrfy_akyuk_1917_2023_10m_3338_v20240309.tif')

gdal_translate('/data/gis/gis_projects/2019/19-301_ABoVE_Biome_Shift/akvegmap_v2/flt32_mrfy_akyuk_1917_2023_10m_3338_v20240309.tif',
               '/data/gis/gis_projects/2019/19-301_ABoVE_Biome_Shift/akvegmap_v2/mrfy_akyuk_1917_2023_10m_3338_v20240309.tif',
               ot='UInt16', of='COG', a_nodata=0, co=c("OVERVIEWS=IGNORE_EXISTING", "RESAMPLING=MODE", "COMPRESS=DEFLATE", "PREDICTOR=2", "BIGTIFF=IF_SAFER", "NUM_THREADS=16"))

```


