---
title: "compile_covar"
author: "Matt Macander"
date: "2025-10-01"
output: html_document
---

Compile covars for full plot buffer dataset
https://code.earthengine.google.com/30031bd7e612cc90c7c14cf06a083092
https://code.earthengine.google.com/?scriptPath=users%2Fmmacander%2Fakveg_map%3Aembeddings%2Fplot_buff_x_covars_v202509

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(tidyverse)
library(fs)
library(sf)
library(mapview)
library(glue)

# wDir <- path('/data/gis/gis_projects/2025/25-176_Red_Dog_Vegetation/task1_shrub_browning/akveg-data/species_data')
akveg_data <- path('/data/gis/raster_base/Alaska/AKVegMap/akveg-working')
geeDir <- path('/data/gis/gis_base/GEE/GEE_Exports/2025_akveg')

options(scipen = 999)

```

```{get export csvs}
covar_csvs <- dir_ls(geeDir, glob='*03_site_visit_all*.csv')
covar_csvs

dir_create(path(akveg_data, 'Data_Input/extract_data/20251003'), mode='2775')
map(covar_csvs, file_move, new_path=path(akveg_data, 'Data_Input/extract_data/20251003'))

# deal with valid col for join (simplest to remove all plot cols except st_vst)
akveg_covar_extract <- read_csv(path(akveg_data, 'Data_Input/extract_data/20251003', '03_site_visit_all_buffer_3338_20250408_x_akveg_covar_v20251003.csv')) |>
  select(-`system:index`, -`.geo`)

akveg_covar_extract_random_emb_yr <- akveg_covar_extract |>
  mutate(emb_yr = sample(2017:2024, size = n(), replace = TRUE))

akveg_covar_extract_random_emb_yr |> count(emb_yr)

emb_csvs <- map(seq(2017, 2024), ~path(akveg_data, 'Data_Input/extract_data/20251003', glue('03_site_visit_all_buffer_3338_20250408_x_satEmb_{.x}_v20251003.csv')))
emb_extract <- map(emb_csvs, read_csv) |>
  bind_rows() |>
  select(-`system:index`, -`.geo`)

extract_w_emb_rand <- akveg_covar_extract_random_emb_yr |>
  left_join(emb_extract)

write_csv(extract_w_emb_rand,
          path(akveg_data, 'Data_Input/extract_data/20251003', '03_site_visit_all_buffer_3338_20250408_x_akveg_covar_emb_rand_v20251003.csv'))

```

```{r compare akvegv2 v21 v21b}
akveg_covar_extract_v21 <- read_csv(path(akveg_data, 'Data_Input/extract_data/20250930', '03_site_visit_all_buffer_3338_20250408_x_akveg_covar.csv')) |>
  select(-`system:index`, -`.geo`,
         -cent_x, -cent_y, -cst_dst, -cvr_mth, -data_tr, -esa_typ, -fire_yr, -homogns, -lat_dd, -long_dd, -obs_dat, -perspct, -plt_dm_, -plt_rd_, -prjct_c,
         -scp_bry, -scp_lch, -scp_vsc, -st_code, -strc_cl, -valid, -zone) 

colnames(akveg_covar_extract_v21)

# akveg_covar_extract_v2 <- read_csv(path(akveg_data, 'Data_Input/extract_data', 'AKVEG_Sites_Covariates_3338.csv'))
akveg_covar_extract_v2_imp_wInd <- read_csv(path(akveg_data, 'Data_Input/extract_data', 'AKVEG_Sites_Covariates_3338_imputed_wIndices.csv')) |>
  select(-`system:index`, -`.geo`,
         -cent_x, -cent_y, -lat_dd, -long_dd, -Shape_Area, -Shape_Leng, 
         -scp_vasc, -scp_bryo, -scp_lich, 
         -plt_rad_m, -obs_date, -cvr_mthd, -perspect, -prjct_cd, -starts_with('s2_0'))
colnames(akveg_covar_extract_v2_imp_wInd)

akveg_covar_extract_v21b <- read_csv(path(akveg_data, 'Data_Input/extract_data/20251003', '03_site_visit_all_buffer_3338_20250408_x_akveg_covar_v20251003.csv')) |>
  select(-`system:index`, -`.geo`)
colnames(akveg_covar_extract_v21b)

df1 <- akveg_covar_extract_v21
df2 <- akveg_covar_extract_v21b

plot_differences <- inner_join(df1, df2, by = "st_vst", suffix = c("_v2", "_v21")) %>%
  mutate(
    across(
      # Select all columns from the first data frame (which now end in _v2)
      .cols = ends_with("_v2"),
      # For each selected column, calculate the absolute difference
      # with its corresponding column from the second data frame (which ends in _v21).
      .fns = ~ (.x - get(str_replace(cur_column(), "_v2$", "_v21"))),
      # Name the new difference columns with a "diff_" prefix and remove the old suffix
      .names = "diff_{str_remove(.col, '_v2$')}"
    )
  ) |>
  relocate(st_vst, starts_with('diff_'))

plot_differences_means <- plot_differences %>%
  select(-st_vst) %>% # Exclude the st_vst column
  summarise(across(everything(), ~mean(.x, na.rm = TRUE))) %>%
  pivot_longer(
    cols = everything(),
    names_to = "variable",
    values_to = "mean_value"
  ) |>
  filter(str_starts(variable, 'diff_'))

# Calculate the mean absolute difference for each matching column
comparison_results <- inner_join(df1, df2, by = "st_vst", suffix = c("_v2", "_v21")) %>%
  # summarise(
  #   across(
  #     .cols = ends_with("_v2"),
  #     .fns = ~ mean(abs(.x - get(str_replace(cur_column(), "_v2$", "_v21"))), na.rm = TRUE),
  #     .names = "diff_{.col}"
  #   )
  # ) %>%
  tidyr::pivot_longer(
    cols = everything(),
    names_to = "variable",
    values_to = "mean_abs_difference"
  ) %>%
  mutate(variable = str_remove_all(variable, "diff_|_v1")) %>%
  arrange(desc(mean_abs_difference))

```

