---
title: "combine_species"
author: "Matt Macander"
date: "2025-09-26"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)

library(tidyverse)
library(fs)
library(sf)
library(mapview)

wDir <- path('/data/gis/gis_projects/2025/25-176_Red_Dog_Vegetation/task1_shrub_browning/akveg-data/species_data')
```

```{r ingest}
csv_files <- dir_ls(wDir, glob='*/cover_*.csv')
combined_data <- map_dfr(csv_files, read_csv, .id = "source_file") |>
  mutate(cvr_pct_i = round(cvr_pct))


combined_wide <- combined_data |>
  select(-source_file, -cvr_pct) |>
  pivot_wider(names_from=group_abbr, values_from=c(cvr_pct_i, presence), names_vary='slowest') |>
  rowwise() |>
  mutate(emb_yr = case_when(obs_yr >= 2017 ~ obs_yr,
                              TRUE ~ sample(c(2017, 2018, 2019, 2020, 2021, 2022, 2023, 2024), size = 1))) |>
  ungroup()

combined_wide |> group_by(emb_yr) |> tally()

write_csv(combined_wide, path(wDir, 'merged_wide_cover_akveg_for_satemb_v20241124.csv'), na="")

```

```{r explore}
betshr <- combined_data |> filter(group_abbr == 'betshr')
betshr |> group_by(st_vst, prjct_cd) |> tally() |> filter(n>1)
betshr |> group_by(zone) |> tally()

betshr_sf <- betshr |>
  st_as_sf(coords=c('cent_x', 'cent_y'), crs=3338)
mapview(betshr_sf, zcol='zone')
mapview(betshr_sf, zcol='zone') + mapview(betshr_sf |> filter(zone == 1), zcol='zone')

years_summ <- betshr |> group_by(obs_yr, fire_yr) |> tally()
fire_check <- betshr |> filter(fire_yr >= obs_yr)

obs_year_summ <- betshr |> group_by(obs_yr) |> tally()
```