---
title: "Compile and normalize physiography data"
author: "Matt Macander"
date: '2022-12-10'
output: html_document
---

```{r setup, include=FALSE}
library(here)
source(here('init.R'))
source(here('../nasa-airborne/init.R'))
# library(fs)
library(terra)
library(spatialEco)
library(gfcanalysis)
library(exactextractr)

knitr::opts_chunk$set(echo = TRUE)

gisArchive <- path('/data/archives/GIS_Archive')
gis <- path('/data/gis')
outDir <- path(gis, 'gis_projects/2021/21-347_NASA_SmallSat/physiography_working')
```

```{r vector phys}
suwa_wetland_vect <- read_sf(path(gis, 'gis_base/Susitna-Watana/ABR__CompDataDeliv/GDBs_delivered_as ZIP/SuWa_11_7_GIS_20170630.gdb'), 
                                  layer='WETLND_VWHAB_Mapping')
st_crs(suwa_wetland_vect)
suwa_wetland_phys <- suwa_wetland_vect %>% 
  st_drop_geometry() %>%
  rename(physiography = physio_title) %>%
  group_by(physiography) %>%
  summarize(n = n(),
            area_sqkm = sum(Shape_Area) / (1000000 * 10.7639)) %>%
  mutate(dataset = 'Susitna Watana Wetland and Habitat Mapping',
         project_id = '14-174',
         map_year = 2014)

suwa_riparian_vect <- read_sf(path(gis, 'gis_base/Susitna-Watana/ABR__CompDataDeliv/GDBs_delivered_as ZIP/SuWa_11_6_GIS_20170630.gdb'), 
                                  layer='RIP_Mapping')
st_crs(suwa_riparian_vect)
suwa_riparian_phys <- suwa_riparian_vect %>% 
  st_drop_geometry() %>%
  rename(physiography = physio_title) %>%
  group_by(physiography) %>%
  summarize(n = n(),
            area_sqkm = sum(Shape_Area) / (1000000 * 10.7639)) %>%
  mutate(dataset = 'Susitna Watana Riparian Mapping',
         project_id = '14-174',
         map_year = 2014)

ykd_phys_x_ecoreg <- read_sf(path(gis, 'gis_projects/2015/15-331_NASA_ABoVE_YK_Delta/ancilllary_data/YK_ecosubsections/YKD_Strata_2019.gdb'),
                             layer='YKD_physiography_x_ecoregion')
st_crs(ykd_phys_x_ecoreg)
ykd_phys <- ykd_phys_x_ecoreg %>%
  st_drop_geometry() %>%
  rename(physiography = PHYSIO_AGGREGATED) %>%
  group_by(physiography) %>%
  summarize(n = n(),
            area_sqkm = sum(Shape_Area) / (100)) %>%
  mutate(dataset = 'Yukon Delta Physiography and Ecoregion Mapping',
         project_id = '15-331',
         map_year = 2015)

kefj_soils <- read_sf(path(gisArchive, '2012/12-316_NPS_ELS_Soil_Mapping_KEFJ/Deliverable/KEFJ_Soils_ELS.gdb'),
                           layer='KEFJ_ABR_Mapping')
st_crs(kefj_soils)
kefj_phys <- kefj_soils %>%
  st_drop_geometry() %>%
  rename(physiography = Physiography) %>%
  group_by(physiography) %>%
  summarize(n = n(),
            area_sqkm = sum(Shape_Area) / (1000000)) %>%
  mutate(dataset = 'Kenai Fjords Soil Mapping',
         project_id = '12-316',
         map_year = 2012)

northern_ak_landscapes <- read_sf(path(gis, 'gis_projects/2018/18-381_ANWR_Land_Cover_w/original_source/subsections_20181023',
                                       'NoAK_Landscapes_2018-10-23_Working_Copy.gdb'),
                                  layer='NoAK_Landscapes_2018')
st_crs(northern_ak_landscapes)
northern_ak_landscapes_phys <- northern_ak_landscapes %>%
  st_drop_geometry() %>%
  rename(physiography = PHYSIOGRAP) %>%
  group_by(physiography) %>%
  summarize(n = n(),
            area_sqkm = sum(Shape_Area) / (1000000)) %>%
  mutate(dataset = 'Northern Alaska Landscapes',
         project_id = '18-381',
         map_year = 2018)

hazenBay_vect <- read_sf(path(gisArchive, '2010/10-263_YK_Delta_Change/YK_Delta_Veg_Change_20110519/YK_Delta_Veg_Change_20110519.gdb'),
                         layer='Hazen_Bay_Veg_TnJ_20110519')
st_crs(hazenBay_vect)
hazenBay_ecotypes <- hazenBay_vect %>%
  st_drop_geometry() %>%
  rename(ecotype = Ecotype) %>%
  group_by(ecotype) %>%
  summarize(n = n(),
            area_sqkm = sum(Shape_Area) / 1000000) %>%
  mutate(dataset = 'Hazen Bay Ecotypes',
         project_id = '10-263',
         map_year = 2011)

elmendorf <- read_sf(path(gisArchive, '2002/02-322_Elmendorf_AFB_ELC/eafb_itu_v6.shp'))
st_crs(elmendorf)
elmendorf_ecotypes <- elmendorf %>% 
  st_drop_geometry() %>%
  rename(ecotype = ECOTYPE) %>%
  group_by(ecotype) %>%
  summarize(n = n(),
            area_sqkm = sum(AREA_METER) / (1000000)) %>%
  mutate(dataset = 'Elmendorf Air Force Base ITU Mapping',
         project_id = '02-322',
         map_year = 2002)

tanana_flats <- read_sf(path(gisArchive,'2002/02-326_Army_Ecosystem_Mngmt/tanana_flats_els_dd84.shp'))
st_crs(tanana_flats)
tanana_flats_ecotypes <- tanana_flats %>%
  st_drop_geometry() %>%
  rename(ecotype = ECOTYPE_N) %>%
  group_by(ecotype) %>%
  summarize(n = n(),
            area_sqkm = sum(AREA_HECTA) / (100)) %>%
  mutate(dataset = 'Tanana Flats ITU Mapping',
         project_id = '02-236',
         map_year = 2002)

yukon_training_area_itu <- read_sf(path(gisArchive, '2002/02-326_Army_Ecosystem_Mngmt/YMA/YMA_ELS_UTM683.shp')) %>%
  clean_names()
st_crs(yukon_training_area_itu)  
yukon_training_area_ecotypes <- yukon_training_area_itu %>%
  st_drop_geometry() %>%
  rename(ecotype = ecotyoe_n) %>%
  group_by(ecotype) %>%
  summarize(n = n(),
            area_sqkm = sum(area_hecta_2) / (100)) %>%
  mutate(dataset = 'Yukon Training Area ITU',
         project_id = '02-326',
         map_year = 2002)


shell_itu <- read_sf(path(gisArchive, '2015/15-159_Shell_Desktop/Data_Deliverable_2016/Habitat_Mapping/Intensive_Scale/ABR_Shell_ITU.gdb'),
                     layer='ITU_Mapping_Shell_2013_2014_2015_hardjoin')
st_crs(shell_itu)  
shell_itu_ecotypes <- shell_itu %>%
  st_drop_geometry() %>%
  rename(ecotype = ecotype_title) %>%
  group_by(ecotype) %>%
  summarize(n = n(),
            area_sqkm = sum(Shape_Area) / (1000000)) %>%
  mutate(dataset = 'Shell ITU Mapping',
         project_id = '15-159',
         map_year = 2015)

vector_phys <- bind_rows(
  suwa_wetland_phys,
  suwa_riparian_phys,
  kefj_phys,
  northern_ak_landscapes_phys
) %>%
  rename(input_class = physiography) %>%
  mutate(input_type = 'vector physiography')

vector_ecotypes <- bind_rows(
  hazenBay_ecotypes,
  elmendorf_ecotypes,
  tanana_flats_ecotypes,
  yukon_training_area_ecotypes,
  shell_itu_ecotypes
) %>%
  rename(input_class = ecotype) %>%
  mutate(input_type = 'vector ecotype')

# write_excel_csv(vector_phys, path(outDir, 'vector_phys_export_20221212.csv'))
# write_excel_csv(vector_ecotypes, path(outDir, 'vector_ecotype_export_20221212.csv'))

```

```{r raster phys}
lacl_soil <- rast(path(gisArchive, '2010/10-352_LACL_Soils/Soil_LS_Model/Outputs/Physiography/phys_from_meco_v05.tif'))
lacl_vat <- foreign::read.dbf(path(gisArchive, '2010/10-352_LACL_Soils/Soil_LS_Model/Outputs/Physiography/phys_from_meco_v05.tif.vat.dbf'))
lacl_phys <- lacl_vat %>%
  rename(physiography = LEG_Physio,
         value = Value) %>%
  mutate(physiography = str_sub(physiography, 6,-1)) %>%
  group_by(value, physiography) %>%
  summarize(area_sqkm = (sum(Count) * 30 * 30) / (1000000)) %>%
  mutate(dataset = 'LACL Soils',
         project_id = '10-352',
         map_year = 2010)

ania_soil <- rast(path(gisArchive, '2013/13-323_NPS_ELS_Soil_Mapping_ANIA_ALAG/ANIA/Deliverable_Soil_LS_Model/Outputs/ANIA_Ecosystem_Mapping.tif'))
ania_vat <- foreign::read.dbf(path(gisArchive, '2013/13-323_NPS_ELS_Soil_Mapping_ANIA_ALAG/ANIA/Deliverable_Soil_LS_Model/Outputs',
                                   'ANIA_Ecosystem_Mapping.tif.vat.dbf'))
ania_phys <- ania_vat %>%
  rename(physiography = phys_de,
         value = Value) %>%
  group_by(value, physiography) %>%
  summarize(area_sqkm = (sum(Count) * 30 * 30) / (1000000)) %>%
  mutate(dataset = 'ANIA Soils',
         project_id = '13-323',
         map_year = 2013)

katm_soil <- rast(path(gisArchive, '2015/15-365_KATM_ELS_mason/001_KATM_Final_Deliverables/KATM_deliverables/GIS/Physical_Modeled',
                       'KATM_Final_Physiography_Map.tif'))
katm_vat <- foreign::read.dbf(path(gisArchive, '2015/15-365_KATM_ELS_mason/001_KATM_Final_Deliverables/KATM_deliverables/GIS/Physical_Modeled',
                                   'KATM_Final_Physiography_Map.tif.vat.dbf'))
katm_phys <- katm_vat %>%
  rename(physiography = phys_de,
         value = Value) %>%
  group_by(value, physiography) %>%
  summarize(area_sqkm = (sum(Count) * 30 * 30) / (1000000)) %>%
  mutate(dataset = 'KATM Soils',
         project_id = '15-365',
         map_year = 2015)

yuch_soil <- rast(path(gisArchive, '2015/15-365_KATM_ELS_mason/002_YUCH_Final_Deliverables/YUCH_deliverables/GIS/Physical_Modeled/YUCH_Physiography.tif'))
yuch_vat <- foreign::read.dbf(path(gisArchive, '2015/15-365_KATM_ELS_mason/002_YUCH_Final_Deliverables/YUCH_deliverables/GIS/Physical_Modeled',
                                   'YUCH_Physiography.tif.vat.dbf'))
yuch_phys <- yuch_vat %>%
  rename(physiography = phys_de,
         value = Value) %>%
  group_by(value, physiography) %>%
  summarize(area_sqkm = (sum(Count) * 30 * 30) / (1000000)) %>%
  mutate(dataset = 'YUCH Soils',
         project_id = '15-365',
         map_year = 2015)

wrst_soil <- rast(path(gisArchive, '2003/03-348_Wrangells_ELS/NPS_Deliverables/grid7_apr08/ecotype_3'))
wrst_vat <- cats(wrst_soil)[[1]]
wrst_ecotypes <- wrst_vat %>%
  rename(ecotype = ECOTYPE,
         value = VALUE) %>%
  group_by(value, ecotype) %>%
  summarize(area_sqkm = (sum(COUNT) * 28.5 * 28.5) / (1000000)) %>%
  mutate(dataset = 'WRST Soils',
         project_id = '03-348',
         map_year = 2003)

arcn_soil <- rast(path(gis, 'gis_projects/2021/21-347_NASA_SmallSat/physiography_working/lc_arcn.tif'))
# arcn_vat <- cats(arcn_soil)[[1]]
arcn_vat <- foreign::read.dbf(path(gis, 'gis_projects/2021/21-347_NASA_SmallSat/physiography_working/lc_arcn.tif.vat.dbf'))
arcn_ecotypes <- arcn_vat %>%
  rename(ecotype = MAP_ECOTYP,
         value = VALUE) %>%
  group_by(value, ecotype) %>%
  summarize(area_sqkm = (sum(COUNT) * 28.5 * 28.5) / (1000000)) %>%
  mutate(dataset = 'ARCN Soils',
         project_id = '08-306',
         map_year = 2008)

shell_extensive_mapeco <- rast(path(gisArchive, '2015/15-159_Shell_Desktop/Data_Deliverable_2016/Habitat_Mapping/Extensive_Scale',
                                    'Shell_Extensive_Map_Ecotypes_Draft_20141227.tif'))
shell_extensive_mapeco_vat <- foreign::read.dbf(path(gisArchive, '2015/15-159_Shell_Desktop/Data_Deliverable_2016/Habitat_Mapping/Extensive_Scale',
                                                     'Shell_Extensive_Map_Ecotypes_Draft_20141227.tif.vat.dbf'))
shell_ecotype <- shell_extensive_mapeco_vat %>%
  rename(ecotype = emeco_ab,
         value = Value) %>%
  group_by(value, ecotype) %>%
  summarize(area_sqkm = (sum(Count) * 30 * 30) / (1000000)) %>%
  mutate(dataset = 'Shell Extensive Ecotype Mapping',
         project_id = '15-159',
         map_year = 2015)

raster_phys <- bind_rows(
  lacl_phys,
  ania_phys,
  katm_phys,
  yuch_phys
) %>%
  rename(input_class = physiography) %>%
  mutate(input_type = 'raster physiography')


raster_ecotypes <- bind_rows(
  wrst_ecotypes,
  arcn_ecotypes,
  shell_ecotype
) %>%
  rename(input_class = ecotype) %>%
  mutate(input_type = 'raster ecotype')

# write_excel_csv(raster_phys, path(outDir, 'raster_phys_export_20221212.csv'))
# write_excel_csv(raster_ecotypes, path(outDir, 'raster_ecotype_export_20221212.csv'))
```

```{r setup for crosswalk}
physiography_lookup_out <- bind_rows(
  vector_phys,
  raster_phys,
  vector_ecotypes,
  raster_ecotypes)
write_excel_csv(physiography_lookup_out, path(outDir, 'physiography_lookup_export_20221212.csv'))

```

```{r reclass vect}
ref_physiography_lookup <- read_xlsx(path(outDir, 'physiography_lookup_20221212.xlsx'), sheet='physiography_lookup')
ref_physiography <- read_xlsx(path(outDir, 'physiography_lookup_20221212.xlsx'), sheet='ref_phys')

datasets <- ref_physiography_lookup %>%
  group_by(dataset) %>%
  tally()

hazenBay_vect_phys <- read_sf(path(gisArchive, '2010/10-263_YK_Delta_Change/YK_Delta_Veg_Change_20110519/YK_Delta_Veg_Change_20110519.gdb'),
                         layer='Hazen_Bay_Veg_TnJ_20110519') %>%
  rename(ecotype = Ecotype) %>%
  rename(geometry = Shape) %>%
  left_join(ref_physiography_lookup %>% 
              filter(dataset == 'Hazen Bay Ecotypes'),
            by=c('ecotype'='input_class')) %>%
  group_by(phys_co, dataset) %>%
  summarize() %>%
  st_cast('MULTIPOLYGON') %>%
  st_cast('POLYGON') %>%
  st_transform(3338)
# mapview(hazenBay_vect_phys)
# write_sf(hazenBay_vect_phys, path(outDir, 'vector_physiography_norm_20221212.gpkg'), layer='hazen_bay')
# write_sf(hazenBay_vect_phys, path(outDir, 'shapefiles_norm', 'hazen_bay.shp'))

elmendorf_vect_phys <- read_sf(path(gisArchive, '2002/02-322_Elmendorf_AFB_ELC/eafb_itu_v6.shp')) %>%
  rename(ecotype = ECOTYPE) %>%
  left_join(ref_physiography_lookup %>% 
              filter(dataset == 'Elmendorf Air Force Base ITU Mapping'),
            by=c('ecotype'='input_class')) %>%
  group_by(phys_co, dataset) %>%
  summarize() %>%
  st_cast('MULTIPOLYGON') %>%
  st_cast('POLYGON') %>%
  st_transform(3338)
# mapview(elmendorf_vect_phys)
# write_sf(elmendorf_vect_phys, path(outDir, 'vector_physiography_norm_20221212.gpkg'), layer='elmendorf')
# write_sf(elmendorf_vect_phys, path(outDir, 'shapefiles_norm', 'elmendorf.shp'))

tanana_flats_vect_phys <- read_sf(path(gisArchive,'2002/02-326_Army_Ecosystem_Mngmt/tanana_flats_els_dd84.shp')) %>%
  rename(ecotype = ECOTYPE_N) %>%
  left_join(ref_physiography_lookup %>% 
              filter(dataset == 'Tanana Flats ITU Mapping'),
            by=c('ecotype'='input_class')) %>%
  group_by(phys_co, dataset) %>%
  summarize() %>%
  st_cast('MULTIPOLYGON') %>%
  st_cast('POLYGON') %>%
  st_transform(3338)
# mapview(tanana_flats_vect_phys)
# write_sf(tanana_flats_vect_phys, path(outDir, 'vector_physiography_norm_20221212.gpkg'), layer='tanana_flats')
# write_sf(tanana_flats_vect_phys, path(outDir, 'shapefiles_norm', 'tanana_flats.shp'))

yukon_training_area_itu <- read_sf(path(gisArchive, '2002/02-326_Army_Ecosystem_Mngmt/YMA/YMA_ELS_UTM683.shp')) %>%
  clean_names() %>%
  st_make_valid() %>%
  rename(ecotype = ecotyoe_n) %>%
  left_join(ref_physiography_lookup %>% 
              filter(dataset == 'Yukon Training Area ITU'),
            by=c('ecotype'='input_class')) %>%
  filter(!is.na(phys_co)) %>%
  group_by(phys_co, dataset) %>%
  summarize() %>%
  st_cast('MULTIPOLYGON') %>%
  st_cast('POLYGON') %>%
  st_transform(3338)
# mapview(yukon_training_area_itu)
# write_sf(yukon_training_area_itu, path(outDir, 'vector_physiography_norm_20221212.gpkg'), layer='yukon_training_area')
# write_sf(yukon_training_area_itu, path(outDir, 'shapefiles_norm', 'yukon_training_area_itu.shp'))


shell_itu <- read_sf(path(gisArchive, '2015/15-159_Shell_Desktop/Data_Deliverable_2016/Habitat_Mapping/Intensive_Scale/ABR_Shell_ITU.gdb'),
                     layer='ITU_Mapping_Shell_2013_2014_2015_hardjoin') %>%
  rename(ecotype = ecotype_title) %>%
  rename(geometry = Shape) %>%
  left_join(ref_physiography_lookup %>% 
              filter(dataset == 'Shell ITU Mapping'),
            by=c('ecotype'='input_class')) %>%
  group_by(phys_co, dataset) %>%
  summarize() %>%
  st_cast('MULTIPOLYGON') %>%
  st_cast('POLYGON') %>%
  st_transform(3338)
# mapview(shell_itu)
# write_sf(shell_itu, path(outDir, 'vector_physiography_norm_20221212.gpkg'), layer='shell_itu')
# write_sf(shell_itu, path(outDir, 'shapefiles_norm', 'shell_itu.shp'))

# suwa_wetland_vect <- read_sf(path(gis, 'gis_base/Susitna-Watana/ABR__CompDataDeliv/GDBs_delivered_as ZIP/SuWa_11_7_GIS_20170630.gdb'),
#                                   layer='WETLND_VWHAB_Mapping') %>%
suwa_wetland_vect <- read_sf(path(gis, 'gis_projects/2021/21-347_NASA_SmallSat/physiography_working/physiography_inputs.gdb'),
                             layer='SuWa_WETLND_VWHAB_Mapping_diss_physio') %>%
  rename(geometry = Shape) %>%
  st_make_valid() %>%
  rename(physiography = physio_title) %>%
  select(physiography) %>%
  left_join(ref_physiography_lookup %>%
              filter(dataset == 'Susitna Watana Wetland and Habitat Mapping'),
            by=c('physiography'='input_class')) %>%
  group_by(phys_co, dataset) %>%
  summarize() %>%
  st_cast('MULTIPOLYGON') %>%
  st_cast('POLYGON') %>%
  st_transform(3338)
  # select(phys_co)
# mapview(suwa_wetland_vect)
# write_sf(suwa_wetland_vect, path(outDir, 'vector_physiography_norm_20221212.gpkg'), layer='suwa_wetland_vect')
# write_sf(suwa_wetland_vect, path(outDir, 'shapefiles_norm', 'suwa_wetland_vect.shp'))

suwa_riparian_vect <- read_sf(path(gis, 'gis_base/Susitna-Watana/ABR__CompDataDeliv/GDBs_delivered_as ZIP/SuWa_11_6_GIS_20170630.gdb'),
                                  layer='RIP_Mapping') %>%
  rename(geometry = Shape) %>%
  st_make_valid() %>%
  rename(physiography = physio_title) %>%
  left_join(ref_physiography_lookup %>%
              filter(dataset == 'Susitna Watana Riparian Mapping'),
            by=c('physiography'='input_class')) %>%
  group_by(phys_co, dataset) %>%
  summarize() %>%
  st_cast('MULTIPOLYGON') %>%
  st_cast('POLYGON') %>%
  st_transform(3338)
# mapview(suwa_riparian_vect)
# write_sf(suwa_riparian_vect, path(outDir, 'vector_physiography_norm_20221212.gpkg'), layer='suwa_riparian_vect')
# write_sf(suwa_riparian_vect, path(outDir, 'shapefiles_norm', 'suwa_riparian_vect.shp'))

# kefj_soils <- read_sf(path(gisArchive, '2012/12-316_NPS_ELS_Soil_Mapping_KEFJ/Deliverable/KEFJ_Soils_ELS.gdb'),
#                            layer='KEFJ_ABR_Mapping') %>%
kefj_soils <- read_sf(path(gis, 'gis_projects/2021/21-347_NASA_SmallSat/physiography_working/physiography_inputs.gdb'),
                           layer='KEFJ_ABR_Physiography_wOcean') %>%
  rename(geometry = Shape) %>%
  rename(physiography = Physiography) %>%
  left_join(ref_physiography_lookup %>% 
              filter(dataset == 'Kenai Fjords Soil Mapping'),
            by=c('physiography'='input_class')) %>%
  group_by(phys_co, dataset) %>%
  summarize() %>%
  st_cast('MULTIPOLYGON') %>%
  st_cast('POLYGON') %>%
  st_transform(3338)
# mapview(kefj_soils)
# write_sf(kefj_soils, path(outDir, 'vector_physiography_norm_20221212.gpkg'), layer='kefj_soils')
# write_sf(kefj_soils, path(outDir, 'shapefiles_norm', 'kefj_soils.shp'))

northern_ak_landscapes <- read_sf(path(gis, 'gis_projects/2018/18-381_ANWR_Land_Cover_w/original_source/subsections_20181023',
                                       'NoAK_Landscapes_2018-10-23_Working_Copy.gdb'),
                                  layer='NoAK_Landscapes_2018') %>%
  rename(geometry = Shape) %>%
  rename(physiography = PHYSIOGRAP) %>%
  left_join(ref_physiography_lookup %>% 
              filter(dataset == 'Northern Alaska Landscapes'),
            by=c('physiography'='input_class')) %>%
  filter(!is.na(phys_co)) %>%
  group_by(phys_co, dataset) %>%
  st_make_valid() %>%
  summarize() %>%
  st_cast('MULTIPOLYGON') %>%
  st_cast('POLYGON') %>%
  st_transform(3338)
# mapview(northern_ak_landscapes)
# write_sf(northern_ak_landscapes, path(outDir, 'vector_physiography_norm_20221212.gpkg'), layer='northern_ak_landscapes')
# write_sf(northern_ak_landscapes, path(outDir, 'shapefiles_norm', 'northern_ak_landscapes.shp'))

phys_vect <- bind_rows(
  hazenBay_vect_phys,
  elmendorf_vect_phys,
  tanana_flats_vect_phys,
  yukon_training_area_itu,
  shell_itu, 
  suwa_wetland_vect, 
  suwa_riparian_vect,
  kefj_soils, 
  northern_ak_landscapes 
) %>%
  left_join(ref_physiography)
write_sf(phys_vect, path(outDir, 'shapefiles_norm', 'phys_vect_v20221213.shp'))

```

```{r reclass raster}
ref_physiography_lookup <- read_xlsx(path(outDir, 'physiography_lookup_20221212.xlsx'), sheet='physiography_lookup')
ref_physiography <- read_xlsx(path(outDir, 'physiography_lookup_20221212.xlsx'), sheet='ref_phys')

reclass_raster_phys <- function(inPath, outPath, datasetName) {
  inRast <- rast(inPath)
  reclass <- ref_physiography_lookup %>%
  filter(dataset == datasetName) %>%
  select(value, phys_co) %>%
  mutate(value = as.integer(value),
         phys_co = as.integer(phys_co)) %>%
  filter(phys_co != 99) %>%
  as.matrix()
  
  # print(reclass)
  
  physRast <- classify(inRast, reclass, others=NA)
  # plot(lacl_phys)
  
  writeRaster(physRast, outPath,
              overwrite=TRUE, gdal=c("COMPRESS=LZW"), datatype='INT1U')
  file_copy(path(gis, 'gis_projects/2021/21-347_NASA_SmallSat/physiography_working/rasters_norm', 'phys_co.clr'),
            glue('{outPath}.clr'),
            overwrite=T)
}

reclass_raster_phys(rast(path(gisArchive, '2010/10-352_LACL_Soils/Soil_LS_Model/Outputs/Physiography/phys_from_meco_v05.tif')),
                    path(gis, 'gis_projects/2021/21-347_NASA_SmallSat/physiography_working/rasters_norm', 'lacl_phys.tif'),
                    'LACL Soils')

reclass_raster_phys(path(gisArchive, '2013/13-323_NPS_ELS_Soil_Mapping_ANIA_ALAG/ANIA/Deliverable_Soil_LS_Model/Outputs/ANIA_Ecosystem_Mapping.tif'),
                    path(gis, 'gis_projects/2021/21-347_NASA_SmallSat/physiography_working/rasters_norm', 'ania_phys.tif'),
                    'ANIA Soils')

reclass_raster_phys(path(gisArchive, '2015/15-365_KATM_ELS_mason/001_KATM_Final_Deliverables/KATM_deliverables/GIS/Physical_Modeled',
                       'KATM_Final_Physiography_Map.tif'),
                    path(gis, 'gis_projects/2021/21-347_NASA_SmallSat/physiography_working/rasters_norm', 'katm_phys.tif'),
                    'KATM Soils')

reclass_raster_phys(path(gisArchive, '2015/15-365_KATM_ELS_mason/002_YUCH_Final_Deliverables/YUCH_deliverables/GIS/Physical_Modeled/YUCH_Physiography.tif'),
                    path(gis, 'gis_projects/2021/21-347_NASA_SmallSat/physiography_working/rasters_norm', 'yuch_phys.tif'),
                    'YUCH Soils')

reclass_raster_phys(path(gisArchive, '2003/03-348_Wrangells_ELS/NPS_Deliverables/grid7_apr08/ecotype_3'),
                    path(gis, 'gis_projects/2021/21-347_NASA_SmallSat/physiography_working/rasters_norm', 'wrst_phys.tif'),
                    'WRST Soils')

reclass_raster_phys(path(gis, 'gis_projects/2021/21-347_NASA_SmallSat/physiography_working/lc_arcn.tif'),
                    path(gis, 'gis_projects/2021/21-347_NASA_SmallSat/physiography_working/rasters_norm', 'arcn_phys.tif'),
                    'ARCN Soils')

reclass_raster_phys(path(gisArchive, '2015/15-159_Shell_Desktop/Data_Deliverable_2016/Habitat_Mapping/Extensive_Scale',
                                    'Shell_Extensive_Map_Ecotypes_Draft_20141227.tif'),
                    path(gis, 'gis_projects/2021/21-347_NASA_SmallSat/physiography_working/rasters_norm', 'shell_ns_ext_phys.tif'),
                    'Shell Extensive Ecotype Mapping')

```
