---
title: "Compile and normalize physiography data"
author: "Matt Macander"
date: '2022-12-10'
output: html_document
---

From H:\programming\abr\nasa-airborne\srlite\phys_model

```{r setup, include=FALSE}
library(here)
# source(here('init.R'))
# source(here('../nasa-airborne/init.R'))
# library(fs)
library(tidyverse)
library(fs)
library(sf)
library(terra)
library(readxl)
library(mapview)
# library(spatialEco)
# library(gfcanalysis)
# library(exactextractr)

knitr::opts_chunk$set(echo = TRUE)

gisArchive <- path('/data/archives/GIS_Archive')
gis <- path('/data/gis')
# outDir <- path(gis, 'gis_projects/2021/21-347_NASA_SmallSat/physiography_working')
```

```{r vector phys}
workingDir <- path(gis, 'gis_projects/2024/24-261_AKVEG_Riparian_BLM/AKVEG_Flooplains_20260129_working.gdb')
outDir <- path(gis, 'gis_projects/2024/24-261_AKVEG_Riparian_BLM/AKVEG_Flooplains_20260130.gdb')

# Northen Alaska Landscapes (Jorgenson)
# From Q:\GIS_Archive\2018\18-381_ANWR_Land_Cover_w\original_source\subsections_20181023\NoAK_Landscapes_2018-10-23_Working_Copy.gdb\NoAK_Landscapes_2018
noak_subsec_vect <- read_sf(path(workingDir), 
  layer='NoAK_Landscapes_2018_edited_2026_edgeRem')
st_crs(noak_subsec_vect)

noak_subsec_phys <- noak_subsec_vect %>% 
  st_drop_geometry() %>%
  rename(physiography = PHYSIOGRAP) %>%
  group_by(physiography) %>%
  summarize(n = n(),
            area_sqkm = sum(Shape_Area) / (1000000 * 10.7639)) %>%
  mutate(dataset = 'NoAK_Landscapes_2018_edited_2026_edgeRem',
         project_id = '18-381',
         map_year = 2018)

# Katmai
katm_phys_vect <- read_sf(path(gisArchive, '2015/15-365_KATM_ELS_mason/15-365.1_katm_soil/soil_ls_model/phys/merged_working/merged_phys_working_20180705.gdb'), 
  layer='phys_working_20180705_overlay_coastal_v01')
st_crs(katm_phys_vect)

katm_phys <- katm_phys_vect %>% 
  st_drop_geometry() %>%
  rename(physiography = Physiography) %>%
  group_by(physiography) %>%
  summarize(n = n(),
            area_sqkm = sum(Shape_Area) / (1000000 * 10.7639)) %>%
  mutate(dataset = 'Katmai physiography vector',
         project_id = '15-365',
         map_year = 2015)

# YUCH
yuch_phys_vect <- read_sf(path(gisArchive, '2015/15-365_KATM_ELS_mason/15-365.4_soils_landscape_and_nrcs_comparison/soil_landscape_model/physiography/riverine/YUCH_Riverine_Phys.gdb'),
  layer='YUCH_Riverine_Physiography_Working')
st_crs(yuch_phys_vect)

yuch_phys <- yuch_phys_vect %>% 
  st_drop_geometry() %>%
  rename(physiography = Physiography) %>%
  group_by(physiography) %>%
  summarize(n = n(),
            area_sqkm = sum(Shape_Area) / (1000000 * 10.7639)) %>%
  mutate(dataset = 'YUCH physiography vector',
         project_id = '15-365',
         map_year = 2015)

# WRST
wrst_subsec_vect <- read_sf(path(workingDir), 
  layer='WRST_Subsections_2007_3338')
st_crs(wrst_subsec_vect)

wrst_phys <- wrst_subsec_vect %>% 
  st_drop_geometry() %>%
  rename(physiography = PHYSIOGRAP) %>%
  group_by(physiography) %>%
  summarize(n = n(),
            area_sqkm = sum(Shape_Area) / (1000000 * 10.7639)) %>%
  mutate(dataset = 'WRST Subsections',
         project_id = '03-348',
         map_year = 2003)

vector_phys <- bind_rows(
  noak_subsec_phys,
  katm_phys,
  yuch_phys,
  wrst_phys
) %>%
  rename(input_class = physiography) %>%
  mutate(input_type = 'vector physiography')

write_excel_csv(vector_phys, path(path_dir(outDir), 'vector_phys_export_20260130.csv'))

```

```{r reclass vect}
workingDir <- path(gis, 'gis_projects/2024/24-261_AKVEG_Riparian_BLM/AKVEG_Flooplains_20260129_working.gdb')
outDir <- path(gis, 'gis_projects/2024/24-261_AKVEG_Riparian_BLM/AKVEG_Flooplains_20260130.gdb')

ref_physiography_lookup <- read_xlsx(path(path_dir(outDir), 'vector_phys_export_20260130.xlsx'), sheet='physiography_lookup')
ref_physiography <- read_xlsx(path(path_dir(outDir), 'vector_phys_export_20260130.xlsx'), sheet='ref_phys')

datasets <- ref_physiography_lookup %>%
  group_by(dataset) %>%
  tally()
datasets

#WRST
wrst_subsec_vect <- read_sf(path(workingDir), 
  layer='WRST_Subsections_2007_3338') %>%
  # rename(geometry = Shape) %>%
  st_make_valid() %>%
  rename(physiography = PHYSIOGRAP) %>%
  left_join(ref_physiography_lookup %>%
              filter(dataset == 'WRST Subsections'),
            by=c('physiography'='input_class')) %>%
  group_by(phys_co, dataset) %>%
  summarize() %>%
  st_cast('MULTIPOLYGON') %>%
  st_cast('POLYGON') %>%
  st_transform(3338)
mapview(wrst_subsec_vect)

wrst_floodplains <- wrst_subsec_vect |>
  filter(phys_co == 3)

wrst_trainingArea <- wrst_subsec_vect |>
  ungroup() |>
  summarize()

mapview(wrst_floodplains) + mapview(wrst_trainingArea)
write_sf(wrst_floodplains, path(outDir), layer='WRST_Floodplains_3338')
write_sf(wrst_trainingArea, path(outDir), layer='WRST_TrainingArea_3338')

#YUCH
yuch_subsec_vect <- read_sf(path(gisArchive, '2015/15-365_KATM_ELS_mason/15-365.4_soils_landscape_and_nrcs_comparison/soil_landscape_model/physiography/riverine/YUCH_Riverine_Phys.gdb'),
  layer='YUCH_Riverine_Physiography_Working') %>%
  select(-phys_co) %>%
  rename(geometry = Shape) %>%
  st_make_valid() %>%
  rename(physiography = Physiography) %>%
  left_join(ref_physiography_lookup %>%
              filter(dataset == 'YUCH physiography vector'),
            by=c('physiography'='input_class')) %>%
  group_by(phys_co, dataset) %>%
  summarize() %>%
  st_cast('MULTIPOLYGON') %>%
  st_cast('POLYGON') %>%
  st_transform(3338)
# mapview(yuch_subsec_vect)

yuch_floodplains <- yuch_subsec_vect |>
  filter(phys_co == 3)

yuch_trainingArea <- yuch_subsec_vect |>
  ungroup() |>
  summarize()

mapview(yuch_floodplains) + mapview(yuch_trainingArea)
write_sf(yuch_floodplains, path(outDir), layer='YUCH_Floodplains_3338')
write_sf(yuch_trainingArea, path(outDir), layer='YUCH_TrainingArea_3338')

#KATM
katm_subsec_vect <- read_sf(path(gisArchive, '2015/15-365_KATM_ELS_mason/15-365.1_katm_soil/soil_ls_model/phys/merged_working/merged_phys_working_20180705.gdb'), 
  layer='phys_working_20180705_overlay_coastal_v01') %>%
  # rename(geometry = Shape) %>%
  st_make_valid() %>%
  rename(physiography = Physiography) %>%
  left_join(ref_physiography_lookup %>%
              filter(dataset == 'Katmai physiography vector'),
            by=c('physiography'='input_class')) %>%
  group_by(phys_co, dataset) %>%
  summarize() %>%
  st_cast('MULTIPOLYGON') %>%
  st_cast('POLYGON') %>%
  st_transform(3338)
mapview(katm_subsec_vect)

katm_floodplains <- katm_subsec_vect |>
  filter(phys_co == 3)

katm_trainingArea <- katm_subsec_vect |>
  ungroup() |>
  summarize()

mapview(katm_floodplains) + mapview(katm_trainingArea)
write_sf(katm_floodplains, path(outDir), layer='KATM_Floodplains_3338')
write_sf(katm_trainingArea, path(outDir), layer='KATM_TrainingArea_3338')

#NoAK Jorgenson 2018
noak_subsec_vect <- read_sf(path(workingDir), 
  layer='NoAK_Landscapes_2018_edited_2026_edgeRem') %>%
  # rename(geometry = Shape) %>%
  st_make_valid() %>%
  rename(physiography = PHYSIOGRAP) %>%
  left_join(ref_physiography_lookup %>%
              filter(dataset == 'NoAK_Landscapes_2018_edited_2026_edgeRem'),
            by=c('physiography'='input_class')) %>%
  group_by(phys_co, dataset) %>%
  summarize() %>%
  st_cast('MULTIPOLYGON') %>%
  st_cast('POLYGON') %>%
  st_transform(3338)
mapview(noak_subsec_vect)

noak_floodplains <- noak_subsec_vect |>
  filter(phys_co == 3)

noak_trainingArea <- noak_subsec_vect |>
  ungroup() |>
  summarize()

mapview(noak_floodplains) + mapview(noak_trainingArea)
write_sf(noak_floodplains, path(outDir), layer='NoAK_Floodplains_3338')
write_sf(noak_trainingArea, path(outDir), layer='NoAK_TrainingArea_3338')

# phys_vect <- bind_rows(
# ) %>%
#   left_join(ref_physiography)
# write_sf(phys_vect, path(outDir, 'shapefiles_norm', 'phys_vect_v20260130.shp'))

```

```{r Jorgenson Floodplains 20260211}
# File at W:\gis_projects\2024\24-261_AKVEG_Riparian_BLM\jorgenson\Floodplains AK_Ecological_Landscapes_20260210\Floodplains AK_Ecological_Landscapes_20260210.mdb
# Floodplains only, not 'trainingArea' or 'non floodplains' explicitly
# Manually merged AK250 coastline with mapped area from Jorgenson 2018 layer (prior version)

# Saved to path(gis, 'gis_projects/2024/24-261_AKVEG_Riparian_BLM/AKVEG_Flooplains_20260211.gdb')

```
